skip_tags: true

image: Visual Studio 2019

platform: x86
configuration: Release

build:
  parallel: true
  project: PDA-Loader.sln

after_build:
    - cd source\plugins\MLAC
    - msbuild -p:Configuration=101
    - msbuild -p:Configuration=130
    - msbuild -p:Configuration=200
    - msbuild -p:Configuration=301
    - cd ..\..\..
    - cmd: publish

artifacts:
    - path: 1.01.7z
      name: 1.01
    - path: 1.30.7z
      name: 1.30
    - path: 2.00.7z
      name: 2.00
    - path: 3.01.7z
      name: 3.01
    - path: 6.00.7z
      name: 6.00